Repository For-Hives/my-makeup, pull requests merged in 2023-07, with the labels that each got.

#254 Feat(#243): Limitation du nombre d'upload & sitemap fix
  src/components/Global/Info.js
  src/components/Profil/Atoms/ModalUpdate/ModalUpdatePortfolioProfil.js
  src/components/Profil/Childs/Views/ViewPortfolioProfil.js
  src/components/Profil/Parents/ResumeProfil.js
  src/pages/api/auth/[...nextauth].js
  src/pages/auth/error.js
  src/pages/auth/signup.js
  src/pages/search.js
  src/pages/sitemap.xml.js
Labels: bug, enhancement

#255 SEO : gtag add
  src/pages/_document.js
Labels: enhancement

#260 BugFix(#258): Hydratation problems
  package.json
  src/components/Global/Card-demo.js
  src/components/Global/Nav.js
  src/components/Profil/Childs/ServiceOffers/OptionsOffers.js
  src/components/Profil/Parents/ResumeProfil.js
  src/components/Profil/Parents/ViewResumeProfil.js
  src/pages/auth/error.js
  src/pages/auth/profil.js
  src/pages/auth/verification-complete.js
  src/pages/contact.js
  src/pages/profil/[username].js
  src/pages/search.js
  src/pages/toutes-les-news.js
Labels: enhancement

#262 trying to fix hydratation
  src/components/Profil/Childs/Views/ViewCoursesProfil.js
  src/components/Profil/Childs/Views/ViewDescriptionProfil.js
  src/components/Profil/Childs/Views/ViewExperiencesProfil.js
  src/components/Profil/Childs/Views/ViewLanguageProfil.js
  src/components/Profil/Childs/Views/ViewLocationProfil.js
  src/components/Profil/Childs/Views/ViewPortfolioProfil.js
  src/components/Profil/Childs/Views/ViewServiceOffersProfil.js
  src/components/Profil/Childs/Views/ViewSkillsProfil.js
  src/components/Profil/Childs/Views/ViewSocialMediaProfil.js
  src/components/Profil/Parents/ViewInfosProfil.js
  src/components/Profil/Parents/ViewResumeProfil.js
Labels: bug

#263 load image in fcp
  src/components/Profil/Parents/ViewResumeProfil.js
Labels: bug

#264 trying to get 100/100 everywere
  src/components/Global/Card-demo.js
  src/components/Profil/Atoms/ModalUpdate/ModalUpdatePortfolioProfil.js
  src/components/Profil/Atoms/ModalUpdate/ModalUpdateResumeProfil.js
  src/components/Profil/Childs/Views/ViewPortfolioProfil.js
  src/components/Profil/Parents/ViewResumeProfil.js
Labels: enhancement

#265 improve cls
  src/components/Profil/Parents/ViewInfosProfil.js
  src/components/Profil/Parents/ViewResumeProfil.js
Labels: bug

#267 Feat(#261): Mettre des valeurs maximales pour tous les champs, côté api & front
  src/components/Global/CTA.js
  src/components/Global/Hero.js
  src/components/Global/Search/SearchBloc.js
  src/components/Profil/Atoms/ModalUpdate/ModalUpdateCoursesProfil.js
  src/components/Profil/Atoms/ModalUpdate/ModalUpdateDescriptionProfil.js
  src/components/Profil/Atoms/ModalUpdate/ModalUpdateExperiencesProfil.js
  src/components/Profil/Atoms/ModalUpdate/ModalUpdateLanguageProfil.js
  src/components/Profil/Atoms/ModalUpdate/ModalUpdateLocationProfil.js
  src/components/Profil/Atoms/ModalUpdate/ModalUpdateResumeProfil.js
  src/components/Profil/Atoms/ModalUpdate/ModalUpdateServiceOffersProfil.js
  src/components/Profil/Atoms/ModalUpdate/ModalUpdateSkillsProfil.js
  src/components/Profil/Atoms/ModalUpdate/ModalUpdateSocialMediaProfil.js
  src/components/Profil/Parents/ResumeProfil.js
  src/pages/auth/signup.js
  src/pages/solutions/pour-les-maquilleuses.js
  src/pages/solutions/pour-les-particuliers.js
Labels: bug, enhancement

#276 Feat(#274): Danger Zone & Socials medias
  README.md
  img.png
  package.json
  src/components/Global/CardDemo.js
  src/components/Global/CompletionProfilProgressBar.js
  src/components/Global/DangerZone.js
  src/components/Global/Footer.js
  src/components/Global/Nav.js
  src/components/Home/Talents.js
  src/components/Profil/Atoms/ModalUpdate/ModalUpdateCoursesProfil.js
  src/components/Profil/Atoms/ModalUpdate/ModalUpdateDescriptionProfil.js
  src/components/Profil/Atoms/ModalUpdate/ModalUpdateExperiencesProfil.js
  src/components/Profil/Atoms/ModalUpdate/ModalUpdateLanguageProfil.js
  src/components/Profil/Atoms/ModalUpdate/ModalUpdateLocationProfil.js
  src/components/Profil/Atoms/ModalUpdate/ModalUpdatePortfolioProfil.js
  src/components/Profil/Atoms/ModalUpdate/ModalUpdateResumeProfil.js
  src/components/Profil/Atoms/ModalUpdate/ModalUpdateServiceOffersProfil.js
  src/components/Profil/Atoms/ModalUpdate/ModalUpdateSkillsProfil.js
  src/components/Profil/Atoms/ModalUpdate/ModalUpdateSocialMediaProfil.js
  src/components/Profil/Childs/Views/ViewLocationProfil.js
  src/components/Profil/Parents/DangerZone.js
  src/components/Profil/Parents/InfosProfil.js
  src/components/Profil/Parents/ResumeProfil.js
  src/components/Profil/Parents/ViewInfosProfil.js
  src/pages/api/sendMail.js
  src/pages/auth/profil.js
  src/pages/blog.js
  src/pages/blog/[id].js
  src/pages/talent/[slug].js
  src/pages/toutes-les-news.js
Labels: enhancement

#343 feat(#78): ajout d'un MOTD sur la page d'acceuil
  src/pages/index.js
  src/services/MOTD.js
Labels: enhancement

#341 feat(#305): test all sitemap route and improve env adaptability
  cypress/e2e/base.cy.js
  src/pages/sitemap.xml.js
Labels: enhancement, test

#360 Feat(#345): Upgrade tests, fixs & little improve
  cypress/e2e/auth/profil-edge.cy.js
  cypress/e2e/auth/profil.cy.js
  cypress/plugins/index.js
  package-lock.json
  src/components/Profil/Atoms/ModalUpdate/ModalUpdateExperiencesProfil.js
  src/components/Profil/Childs/CoursesProfil.js
  src/components/Profil/Childs/DescriptionProfil.js
  src/components/Profil/Childs/ExperiencesProfil.js
  src/components/Profil/Childs/LanguageProfil.js
  src/components/Profil/Childs/LocationProfil.js
  src/components/Profil/Childs/PortfolioProfil.js
  src/components/Profil/Childs/ServiceOffers/DescriptionPriceOffer.js
  src/components/Profil/Childs/ServiceOffers/OptionsOffers.js
  src/components/Profil/Childs/ServiceOffers/ServiceOffersProfil.js
  src/components/Profil/Childs/SkillsProfil.js
  src/components/Profil/Childs/SocialMediaProfil.js
  src/components/Profil/Childs/Views/ViewCoursesProfil.js
  src/components/Profil/Childs/Views/ViewDescriptionProfil.js
  src/components/Profil/Childs/Views/ViewExperiencesProfil.js
  src/components/Profil/Childs/Views/ViewLanguageProfil.js
  src/components/Profil/Childs/Views/ViewLocationProfil.js
  src/components/Profil/Childs/Views/ViewServiceOffersProfil.js
  src/components/Profil/Childs/Views/ViewSkillsProfil.js
  src/components/Profil/Childs/Views/ViewSocialMediaProfil.js
  src/components/Profil/Parents/InfosProfil.js
  src/components/Profil/Parents/ResumeProfil.js
  src/components/Profil/Parents/ViewResumeProfil.js
  src/pages/auth/profil.js
Labels: enhancement, test

#361 Feat(#323): Gcp & Analytics fixs, design, search console, validation to prod from google
  public/assets/signin-assets/facebook_logo.svg
  public/assets/signin-assets/google_logo.svg
  src/components/Global/CTA.js
  src/components/Global/Search/SearchBloc.js
  src/pages/auth/signin.js
  src/pages/auth/signup.js
Labels: bug, enhancement, global

#366 Feat(#312): Search & fix tests
  cypress/e2e/auth/profil-edge.cy.js
  cypress/e2e/auth/profil-update-then-search.cy.js
  src/components/Profil/Atoms/ModalUpdate/ModalUpdateResumeProfil.js
Labels: bug, enhancement, test

#367 Feat(#google): re design button auth
  src/pages/auth/signin.js
  src/pages/auth/signup.js
Labels: enhancement, global

#370 Feat(#ergonomy-google): fix ergonomy cta
  src/components/Global/CTA.js
Labels: bug, enhancement

#374 [Elden Thing] - Liste de petit truc de secu et de ci
  .env.exemple
  .github/workflows/build-test.yml
  .github/workflows/deploy-preprod.yml
  .github/workflows/deploy-prod.yml
  Dockerfile
  cypress.config.js
  cypress/cypress-ci-run.mjs
  cypress/cypress-spec-split.js
  cypress/e2e/auth/profil.cy.js
  src/components/Global/Search/SearchBloc.js
  src/components/Profil/Atoms/ModalUpdate/ModalUpdatePortfolioProfil.js
  src/components/Profil/Atoms/ModalUpdate/ModalUpdateResumeProfil.js
  src/pages/api/auth/[...nextauth].js
  src/pages/auth/init-account.js
  src/pages/auth/profil.js
  src/pages/blog.js
  src/pages/blog/[id].js
  src/pages/index.js
  src/pages/profil/[username].js
  src/pages/search.js
  src/pages/site-map.js
  src/pages/sitemap.xml.js
  src/pages/talent/[slug].js
  src/pages/toutes-les-news.js
  src/services/MOTD.js
  src/services/PatchMeMakeup.js
Labels: help wanted

#388 fix ci
  Dockerfile
Labels: bug

#391 Bugfix(error-on-title)
  src/pages/solutions/pour-les-particuliers.js
Labels: bug

#394 Feat(#386): Bug/Feat, refactor init account
  src/pages/auth/init-account.js
Labels: enhancement

#395 Bugfix(seo): Cannonical link failed
  src/pages/404.js
Labels: enhancement

#411 chores(): invalid conf in production
  Dockerfile
  cypress.config.js
  src/pages/api/auth/[...nextauth].js
Labels: chore
