Repository For-Hives/my-makeup, pull requests merged in 2023-06, with the labels that each got.

#120 feat(#26): ✨ add page "Pourquoi My Makeup ?" with advantages of joining the platform as a makeup artist.
  src/components/Global/Hero.js
  src/components/Maquilleuse/Advantages.js
  src/pages/index.js
  src/pages/maquilleuse.js
Labels: enhancement

#128 ajout d'un point d'exclamation
  src/pages/index.js
Labels: enhancement

#119 feat(#65): ✨ créer une nouvelle page pour l'initialisation du compte utilisateur
  .husky/pre-commit
  src/components/Global/CTA.js
  src/components/Global/Nav.js
  src/components/Home/Collaboration.js
  src/components/Profil/Atoms/ModalUpdate/ModalUpdateResumeProfil.js
  src/components/Profil/Parents/InfosProfil.js
  src/components/Profil/Parents/ResumeProfil.js
  src/middleware.js
  src/pages/api/auth/[...nextauth].js
  src/pages/auth/index.js
  src/pages/auth/init-account.js
  src/pages/auth/profil.js
  src/pages/auth/signin.js
  src/pages/auth/signup.js
Labels: enhancement

#133 (#feat 57): Page de contact
  .env.exemple
  package.json
  src/pages/_app.js
  src/pages/api/sendMail.js
  src/pages/auth/signin.js
  src/pages/auth/signup.js
  src/pages/contact.js
  src/styles/globals.css
Labels: enhancement

#143 feat(#65): ✨ créer une nouvelle page pour l'initialisation du compte utilisateur
  src/components/Profil/Atoms/ModalUpdate/ModalUpdateCoursesProfil.js
  src/components/Profil/Atoms/ModalUpdate/ModalUpdateDescriptionProfil.js
  src/components/Profil/Atoms/ModalUpdate/ModalUpdateExperiencesProfil.js
  src/components/Profil/Atoms/ModalUpdate/ModalUpdateLanguageProfil.js
  src/components/Profil/Atoms/ModalUpdate/ModalUpdateLocationProfil.js
  src/components/Profil/Atoms/ModalUpdate/ModalUpdatePortfolioProfil.js
  src/components/Profil/Atoms/ModalUpdate/ModalUpdateResumeProfil.js
  src/components/Profil/Atoms/ModalUpdate/ModalUpdateServiceOffersProfil.js
  src/components/Profil/Atoms/ModalUpdate/ModalUpdateSkillsProfil.js
  src/components/Profil/Atoms/ModalUpdate/ModalUpdateSocialMediaProfil.js
  src/pages/api/auth/[...nextauth].js
  src/pages/api/sendMail.js
  src/pages/auth/error.js
  src/pages/auth/init-account.js
  src/pages/auth/profil.js
  src/pages/auth/signup.js
  src/pages/auth/verification-complete.js
  src/pages/auth/verification-wall.js
  src/pages/blog/[id].js
  src/services/PatchMeMakeup.js
Labels: enhancement

#148 feat(#134) : optimisation des images du blog, replace img by Image
  package.json
  src/components/Global/Layout.js
  src/pages/blog/[id].js
  src/styles/blog.css
Labels: enhancement

#149 feat(#22) : page pourquoi my makeup, pour les particulier
  src/components/Maquilleuse/AdvantagesMaquillleuse.js
  src/components/Particulier/AdvantagesParticulier.js
  src/pages/maquilleuse.js
  src/pages/particulier.js
Labels: enhancement

#151 feat(#150) : Trouver des maquilleuses
  src/components/Global/Footer.js
  src/pages/particulier/trouver-une-maquilleuse.js
Labels: enhancement

#158 feat(#40,37...): Pages à Gogo, SSG à Gogo, commentaires, et clean de certains composants
  package.json
  src/components/Global/CTA.js
  src/components/Global/Footer.js
  src/components/Global/Nav.js
  src/components/Home/Collaboration.js
  src/components/Home/Talents.js
  src/components/Profil/Atoms/ModalUpdate/ModalUpdateCoursesProfil.js
  src/components/Profil/Atoms/ModalUpdate/ModalUpdateDescriptionProfil.js
  src/components/Profil/Atoms/ModalUpdate/ModalUpdateExperiencesProfil.js
  src/components/Profil/Atoms/ModalUpdate/ModalUpdateLanguageProfil.js
  src/components/Profil/Atoms/ModalUpdate/ModalUpdateLocationProfil.js
  src/components/Profil/Atoms/ModalUpdate/ModalUpdatePortfolioProfil.js
  src/components/Profil/Atoms/ModalUpdate/ModalUpdateResumeProfil.js
  src/components/Profil/Atoms/ModalUpdate/ModalUpdateServiceOffersProfil.js
  src/components/Profil/Atoms/ModalUpdate/ModalUpdateSkillsProfil.js
  src/components/Profil/Atoms/ModalUpdate/ModalUpdateSocialMediaProfil.js
  src/pages/_app.js
  src/pages/a-propos.js
  src/pages/affiliation.js
  src/pages/auth/profil.js
  src/pages/blog.js
  src/pages/cgu.js
  src/pages/cgv.js
  src/pages/help.js
  src/pages/index.js
  src/pages/maquilleuse.js
  src/pages/maquilleuse/partenaires.js
  src/pages/maquilleuse/partenariats.js
  src/pages/mentions-legales.js
  src/pages/parrainage.js
  src/pages/particulier/centraliser-ses-recherches.js
  src/pages/particulier/explorer-les-profils.js
  src/pages/particulier/trouver-une-maquilleuse.js
  src/pages/recrutement.js
  src/pages/site-map.js
  src/pages/solutions/pour-les-maquilleuses.js
  src/pages/solutions/pour-les-particuliers.js
  src/pages/talent/[slug].js
  src/pages/toutes-les-news.js
  src/services/PatchMeMakeup.js
  src/services/utils.js
Labels: enhancement

#172 fix prod
  src/components/Profil/Childs/Views/ViewLanguageProfil.js
  src/components/Profil/Parents/ViewInfosProfil.js
  src/components/Profil/Parents/ViewResumeProfil.js
  src/styles/blog.css
Labels: enhancement

#181 fix auth profil, redirect server side
  src/components/Profil/Childs/Views/ViewCoursesProfil.js
  src/components/Profil/Childs/Views/ViewServiceOffersProfil.js
  src/components/Profil/Childs/Views/ViewSkillsProfil.js
  src/components/Profil/Parents/ViewInfosProfil.js
  src/components/Profil/Parents/ViewResumeProfil.js
  src/pages/auth/profil.js
  src/pages/profil/[username].js
Labels: bug

#216 Feat(#215): Optimisation unlighthouse
  src/components/Global/Card-demo.js
  src/components/Global/Footer.js
  src/components/Global/Hero.js
  src/components/Global/Nav.js
  src/components/Global/Search/FullSearchBloc.js
  src/components/Global/Signature.js
  src/components/Home/Collaboration.js
  src/components/Home/Presentation.js
  src/components/Home/Project.js
  src/components/Home/Talents.js
  src/components/Profil/Atoms/ModalUpdate/ModalUpdateCoursesProfil.js
  src/components/Profil/Atoms/ModalUpdate/ModalUpdateDescriptionProfil.js
  src/components/Profil/Atoms/ModalUpdate/ModalUpdateExperiencesProfil.js
  src/components/Profil/Atoms/ModalUpdate/ModalUpdateLanguageProfil.js
  src/components/Profil/Atoms/ModalUpdate/ModalUpdateLocationProfil.js
  src/components/Profil/Atoms/ModalUpdate/ModalUpdatePortfolioProfil.js
  src/components/Profil/Atoms/ModalUpdate/ModalUpdateResumeProfil.js
  src/components/Profil/Atoms/ModalUpdate/ModalUpdateServiceOffersProfil.js
  src/components/Profil/Atoms/ModalUpdate/ModalUpdateSkillsProfil.js
  src/components/Profil/Atoms/ModalUpdate/ModalUpdateSocialMediaProfil.js
  src/components/Profil/Atoms/ToggleButton.js
  src/components/Profil/Childs/CoursesProfil.js
  src/components/Profil/Childs/DescriptionProfil.js
  src/components/Profil/Childs/ExperiencesProfil.js
  src/components/Profil/Childs/LanguageProfil.js
  src/components/Profil/Childs/LocationProfil.js
  src/components/Profil/Childs/PortfolioProfil.js
  src/components/Profil/Childs/ServiceOffers/DescriptionPriceOffer.js
  src/components/Profil/Childs/ServiceOffers/OptionsOffers.js
  src/components/Profil/Childs/ServiceOffers/ServiceOffersProfil.js
  src/components/Profil/Childs/SkillsProfil.js
  src/components/Profil/Childs/SocialMediaProfil.js
  src/components/Profil/Childs/Views/ViewContainer.js
  src/components/Profil/Childs/Views/ViewCoursesProfil.js
  src/components/Profil/Childs/Views/ViewDescriptionProfil.js
  src/components/Profil/Childs/Views/ViewExperiencesProfil.js
  src/components/Profil/Childs/Views/ViewLanguageProfil.js
  src/components/Profil/Childs/Views/ViewLocationProfil.js
  src/components/Profil/Childs/Views/ViewPortfolioProfil.js
  src/components/Profil/Childs/Views/ViewServiceOffersProfil.js
  src/components/Profil/Childs/Views/ViewSkillsProfil.js
  src/components/Profil/Childs/Views/ViewSocialMediaProfil.js
  src/components/Profil/Parents/ResumeProfil.js
  src/components/Profil/Parents/ViewResumeProfil.js
  src/pages/auth/signin.js
  src/pages/auth/signup.js
  src/pages/auth/verification-complete.js
  src/pages/auth/verification-wall.js
  src/pages/blog.js
  src/pages/blog/[id].js
  src/pages/contact.js
  src/pages/search.js
  src/pages/toutes-les-news.js
Labels: enhancement

#213 Feat(#160): Génération de sitemap
  next-sitemap.config.js
  package.json
  public/robots.txt
  src/pages/sitemap.xml.js
Labels: enhancement

#219 fix
  src/components/Global/Card-demo.js
  src/components/Global/Footer.js
Labels: enhancement

#220 unlighthouse opti - reach lighhouse score
  src/components/Global/CTA.js
  src/pages/pourquoi-rejoindre-my-makeup-en-tant-que-maquilleuse.js
  src/pages/toutes-les-news.js
Labels: enhancement

#221 fix errors log
  public/assets/brand/001-dribbble.svg
  public/assets/brand/002-VK.svg
  public/assets/brand/003-twitter.svg
  public/assets/brand/004-flickr.svg
  public/assets/brand/005-twitter.svg
  public/assets/brand/007-skype.svg
  public/assets/brand/008-tumblr.svg
  public/assets/brand/009-deviantart.svg
  public/assets/brand/010-google plus.svg
  public/assets/brand/011-blogger.svg
  public/assets/brand/012-pinterest.svg
  public/assets/brand/013-paypal.svg
  public/assets/brand/014-quora.svg
  public/assets/brand/015-evernote.svg
  public/assets/brand/016-bebo.svg
  public/assets/brand/018-zerply logo.svg
  public/assets/brand/019-stumbleupon.svg
  public/assets/brand/020-digg.svg
  public/assets/brand/021-ask.svg
  public/assets/brand/022-evernote.svg
  public/assets/brand/023-stack overflow.svg
  public/assets/brand/024-spotify.svg
  public/assets/brand/025-diigo.svg
  public/assets/brand/026-snapchat.svg
  public/assets/brand/027-whatsapp.svg
  public/assets/brand/028-periscope.svg
  public/assets/brand/029-vimeo.svg
  public/assets/brand/031-technorati.svg
  public/assets/brand/032-behance.svg
  public/assets/brand/033-youtube.svg
  public/assets/brand/034-dropbox.svg
  public/assets/brand/035-odnoklassniki.svg
  public/assets/brand/036-android.svg
  public/assets/brand/038-google plus.svg
  public/assets/brand/039-myspace.svg
  public/assets/brand/040-xing.svg
  public/assets/brand/041-yelp.svg
  public/assets/brand/042-badoo.svg
  public/assets/brand/043-rss.svg
  public/assets/brand/044-github.svg
  public/assets/brand/045-etsy.svg
  public/assets/brand/046-yahoo.svg
  public/assets/brand/047-instagram.svg
  public/assets/brand/048-windows.svg
  public/assets/brand/049-apple.svg
  public/assets/brand/050-email.svg
  public/assets/brand/051-phone.svg
  public/assets/brand/052-website.svg
Labels: enhancement

#222 Feat(#218): Badge pro condition
  src/pages/search.js
Labels: enhancement

#223 Feat(#97): Suppression des avis / stars pour le moment
  public/assets/404Cat.webp
  public/assets/vectorials-used/AED38BED.jpg
  public/assets/vectorials-used/cat404.ai
  public/assets/vectorials-used/cat404.png
  public/assets/vectorials-used/cat404.svg
  src/components/Profil/Atoms/ModalUpdate/ModalUpdateCoursesProfil.js
  src/components/Profil/Atoms/ModalUpdate/ModalUpdateDescriptionProfil.js
  src/components/Profil/Atoms/ModalUpdate/ModalUpdateExperiencesProfil.js
  src/components/Profil/Atoms/ModalUpdate/ModalUpdateLanguageProfil.js
  src/components/Profil/Atoms/ModalUpdate/ModalUpdateLocationProfil.js
  src/components/Profil/Atoms/ModalUpdate/ModalUpdatePortfolioProfil.js
  src/components/Profil/Atoms/ModalUpdate/ModalUpdateResumeProfil.js
  src/components/Profil/Atoms/ModalUpdate/ModalUpdateServiceOffersProfil.js
  src/components/Profil/Atoms/ModalUpdate/ModalUpdateSkillsProfil.js
  src/components/Profil/Atoms/ModalUpdate/ModalUpdateSocialMediaProfil.js
  src/components/Profil/Childs/CoursesProfil.js
  src/components/Profil/Childs/DescriptionProfil.js
  src/components/Profil/Childs/ExperiencesProfil.js
  src/components/Profil/Childs/LanguageProfil.js
  src/components/Profil/Childs/LocationProfil.js
  src/components/Profil/Childs/PortfolioProfil.js
  src/components/Profil/Childs/ServiceOffers/ServiceOffersProfil.js
  src/components/Profil/Childs/SkillsProfil.js
  src/components/Profil/Childs/SocialMediaProfil.js
  src/components/Profil/Parents/InfosProfil.js
  src/components/Profil/Parents/ResumeProfil.js
  src/components/Profil/Parents/ViewResumeProfil.js
  src/pages/404.js
  src/pages/auth/profil.js
  src/pages/search.js
Labels: enhancement

#247 Bugfix(#236): signup alternative background
  README.md
  next.config.js
  public/assets/back_alternative.png
  public/assets/bg_makeup_alternative.webp
  public/assets/pp_makeup_alternative.png
  public/assets/screenshot.png
  src/components/Global/Footer.js
  src/components/Global/Nav.js
  src/components/Global/Signature.js
  src/components/Home/Collaboration.js
  src/components/Home/Presentation.js
  src/components/Maquilleuse/AdvantagesMaquillleuse.js
  src/components/Particulier/AdvantagesParticulier.js
  src/components/Profil/Atoms/ModalUpdate/ModalUpdateDescriptionProfil.js
  src/components/Profil/Atoms/ModalUpdate/ModalUpdateExperiencesProfil.js
  src/components/Profil/Atoms/ModalUpdate/ModalUpdateLocationProfil.js
  src/components/Profil/Atoms/ModalUpdate/ModalUpdateResumeProfil.js
  src/components/Profil/Atoms/ModalUpdate/ModalUpdateSocialMediaProfil.js
  src/components/Profil/Parents/ResumeProfil.js
  src/components/Profil/Parents/ViewResumeProfil.js
  src/pages/404.js
  src/pages/a-propos.js
  src/pages/api/sendMail.js
  src/pages/auth/error.js
  src/pages/auth/init-account.js
  src/pages/auth/profil.js
  src/pages/auth/signin.js
  src/pages/auth/signup.js
  src/pages/auth/verification-complete.js
  src/pages/auth/verification-wall.js
  src/pages/blog.js
  src/pages/blog/[id].js
  src/pages/cgu.js
  src/pages/contact.js
  src/pages/index.js
  src/pages/maquilleuse/partenariats.js
  src/pages/particulier/centraliser-ses-recherches.js
  src/pages/particulier/explorer-les-profils.js
  src/pages/particulier/trouver-une-maquilleuse.js
  src/pages/politique-de-confidentialite.js
  src/pages/pourquoi-rejoindre-my-makeup-en-tant-que-maquilleuse.js
  src/pages/pourquoi-utiliser-my-makeup-en-tant-que-particulier.js
  src/pages/profil/[username].js
  src/pages/search.js
  src/pages/site-map.js
  src/pages/sitemap.xml.js
  src/pages/solutions/pour-les-maquilleuses.js
  src/pages/solutions/pour-les-particuliers.js
  src/pages/talent/[slug].js
  src/pages/toutes-les-news.js
Labels: bug, enhancement
