Repository For-Hives/my-makeup, pull requests merged in 2023-05, with the labels that each got.

#86 fix(#85): 🐛 corriger(search.js) : changer la clé de l'élément de la liste de résultats pour correspondre à la nouvelle structure de données
  src/pages/search.js
Labels: bug

#103 Fix prod problems transition component
  package.json
  src/components/Profil/Parents/ResumeProfil.js
Labels: enhancement

#106 feat(#95): Middleware pour le status d'auth
  src/middleware.js
  src/pages/profil.js
Labels: enhancement

#116 🆕 ajout(.imgbotconfig) : ajouter la configuration ImgBot
  .imgbotconfig
Labels: documentation, enhancement

#118 fix(#91): 🔥supprimer le logo inutile
  src/components/Global/Nav.js
Labels: bug

#117 refactor(#90) : 🔨 réorganiser le code pour améliorer la lisibilité
  src/pages/search.js
Labels: bug

#105 fix(#85): 🐛 ajouter les images aux resultats de la recherche
  src/pages/search.js
Labels: enhancement
