Repository For-Hives/my-makeup, pull requests merged in 2023-08, with the labels that each got.

#412 Fix: fail pp set
  .github/workflows/build-test.yml
  cypress.config.js
  cypress/e2e/auth/profil-edge.cy.js
  cypress/e2e/auth/profil-update-then-search.cy.js
  cypress/e2e/auth/profil.cy.js
  cypress/e2e/base.cy.js
  src/components/Profil/Parents/ResumeProfil.js
  src/pages/404.js
Labels: bug

#422 Corriger les doubles / dans la sitemap
  .github/workflows/build-test.yml
  .github/workflows/deploy-preprod.yml
  .github/workflows/deploy-prod.yml
Labels: bug

#421 corriger le crash dans la recherche de mauilleuse si pas images de profile
  .eslintrc.json
  cypress/e2e/auth/profil.cy.js
  src/pages/search.js
Labels: bug

#423 Setup SonnarQube
  .github/workflows/build-test.yml
  .gitignore
  sonar-project.properties
Labels: chore

#426 Feat(#425): fallback blocking
  src/pages/blog/[id].js
  src/pages/profil/[username].js
  src/pages/talent/[slug].js
Labels: chore

#431 trim and lowercase
  src/components/Profil/Parents/ResumeProfil.js
  src/pages/auth/signup.js
Labels: feature

#461 Feat(#459): 0km & affichage de plusieurs services à la fois
  prettier.config.js
  src/components/Profil/Atoms/ModalUpdate/ModalUpdateServiceOffersProfil.js
  src/components/Profil/Childs/Views/ViewLocationProfil.js
  src/components/Profil/Childs/Views/ViewServiceOffersProfil.js
  src/components/Profil/Parents/ViewResumeProfil.js
  src/pages/blog/[id].js
  src/pages/talent/[slug].js
  src/styles/globals.css
Labels: bug
